#!/bin/bash

# setup_project_structure.sh
# Script to create complete directory structure for Medical Ultrasound Reporting Assistant

set -e  # Exit on error

PROJECT_NAME="medical-ultrasound-reporting-assistant"
echo "Creating project structure: $BuAli"

# Create root directory
mkdir -p $PROJECT_NAME
cd $PROJECT_NAME

# ============================================
# .github
# ============================================
echo "Creating .github structure..."
mkdir -p .github/workflows
mkdir -p .github/ISSUE_TEMPLATE

cat > .github/workflows/.gitkeep << EOF
# Placeholder for GitHub Actions workflows
EOF

cat > .github/ISSUE_TEMPLATE/.gitkeep << EOF
# Placeholder for issue templates
EOF

# ============================================
# docs
# ============================================
echo "Creating docs structure..."
mkdir -p docs

touch docs/README.md
touch docs/ARCHITECTURE.md
touch docs/TRAINING_GUIDE.md
touch docs/WEAK_SUPERVISION.md
touch docs/NOISE_HANDLING.md
touch docs/DATA_PREPARATION.md
touch docs/API_REFERENCE.md
touch docs/DEPLOYMENT.md
touch docs/CONTRIBUTING.md

# ============================================
# configs
# ============================================
echo "Creating configs structure..."
mkdir -p configs/models
mkdir -p configs/pipelines

touch configs/default.yaml
touch configs/production.yaml
touch configs/development.yaml

# Model configs
touch configs/models/asr.yaml
touch configs/models/ner.yaml
touch configs/models/content_filter.yaml
touch configs/models/sentence_ranker.yaml
touch configs/models/llm.yaml

# Pipeline configs
touch configs/pipelines/weak_supervision.yaml
touch configs/pipelines/production.yaml
touch configs/pipelines/evaluation.yaml

touch configs/logging.yaml

# ============================================
# data (with .gitkeep for git tracking)
# ============================================
echo "Creating data structure..."

# Raw data
mkdir -p data/raw/audio/{train,validation,test}
mkdir -p data/raw/reports/{train,validation,test}

cat > data/raw/.gitkeep << EOF
# Raw data directory - contents are git-ignored
# Place your audio files and reports here following the structure in docs/DATA_PREPARATION.md
EOF

touch data/raw/pairs.csv

# Processed data
mkdir -p data/processed/transcripts/{train,validation,test}
mkdir -p data/processed/aligned/{train,validation,test}
mkdir -p data/processed/filtered/{train,validation,test}
mkdir -p data/processed/entities/{train,validation,test}
mkdir -p data/processed/synthetic/{templates,generated}

cat > data/processed/.gitkeep << EOF
# Processed data - generated by preprocessing scripts
EOF

# Dictionaries
mkdir -p data/dictionaries/organs

touch data/dictionaries/organs/liver.json
touch data/dictionaries/organs/kidney.json
touch data/dictionaries/organs/gallbladder.json
touch data/dictionaries/organs/spleen.json
touch data/dictionaries/organs/pancreas.json
touch data/dictionaries/organs/bladder.json
touch data/dictionaries/organs/uterus.json
touch data/dictionaries/organs/ovary.json
touch data/dictionaries/organs/prostate.json

touch data/dictionaries/measurements_units.json
touch data/dictionaries/findings_taxonomy.json
touch data/dictionaries/normal_ranges.json
touch data/dictionaries/noise_patterns.json
touch data/dictionaries/correction_indicators.json
touch data/dictionaries/synonyms_fa.json
touch data/dictionaries/synonyms_en.json
touch data/dictionaries/abbreviations.json
touch data/dictionaries/fa_en_mapping.json

# Templates
mkdir -p data/templates

touch data/templates/abdomen_ultrasound.json
touch data/templates/pelvic_ultrasound.json
touch data/templates/obstetric_ultrasound.json
touch data/templates/thyroid_ultrasound.json
touch data/templates/breast_ultrasound.json
touch data/templates/vascular_ultrasound.json

# Model cache
mkdir -p data/models_cache
cat > data/models_cache/.gitkeep << EOF
# Cache for downloaded pretrained models
EOF

# ============================================
# models (git-ignored, for trained models)
# ============================================
echo "Creating models structure..."

mkdir -p models/asr/whisper-large-v3-medical
mkdir -p models/asr/checkpoints

mkdir -p models/content_filter/bert-fa-content-filter
mkdir -p models/content_filter/checkpoints

mkdir -p models/sentence_ranker/ranker-v1
mkdir -p models/sentence_ranker/checkpoints

mkdir -p models/ner/bert-fa-medical-ner
mkdir -p models/ner/checkpoints

mkdir -p models/llm/mixtral-medical-lora
mkdir -p models/llm/checkpoints

touch models/model_registry.json

cat > models/.gitkeep << EOF
# Trained models directory - contents are git-ignored
# Models will be saved here during training
EOF

# ============================================
# src (main source code)
# ============================================
echo "Creating src structure..."

# Core
mkdir -p src/core
touch src/__init__.py
touch src/core/__init__.py
touch src/core/config.py
touch src/core/logger.py
touch src/core/exceptions.py
touch src/core/constants.py

# Preprocessing
mkdir -p src/preprocessing/audio
mkdir -p src/preprocessing/text

touch src/preprocessing/__init__.py
touch src/preprocessing/audio/__init__.py
touch src/preprocessing/audio/loader.py
touch src/preprocessing/audio/vad.py
touch src/preprocessing/audio/segmentation.py
touch src/preprocessing/audio/enhancer.py
touch src/preprocessing/audio/augmentation.py

touch src/preprocessing/text/__init__.py
touch src/preprocessing/text/normalizer.py
touch src/preprocessing/text/cleaner.py

# Alignment (NEW - for weak supervision)
mkdir -p src/alignment

touch src/alignment/__init__.py
touch src/alignment/report_aligner.py
touch src/alignment/sentence_matcher.py
touch src/alignment/entity_aligner.py
touch src/alignment/confidence_scorer.py

# Filtering (NEW - for noise handling)
mkdir -p src/filtering

touch src/filtering/__init__.py
touch src/filtering/content_filter.py
touch src/filtering/sentence_ranker.py
touch src/filtering/noise_detector.py
touch src/filtering/correction_handler.py
touch src/filtering/deduplicator.py

# Models
mkdir -p src/models/asr
mkdir -p src/models/content_filter
mkdir -p src/models/sentence_ranker
mkdir -p src/models/ner
mkdir -p src/models/generation

touch src/models/__init__.py

touch src/models/asr/__init__.py
touch src/models/asr/whisper.py
touch src/models/asr/trainer.py
touch src/models/asr/inference.py

touch src/models/content_filter/__init__.py
touch src/models/content_filter/bert_classifier.py
touch src/models/content_filter/trainer.py
touch src/models/content_filter/inference.py

touch src/models/sentence_ranker/__init__.py
touch src/models/sentence_ranker/ranker_model.py
touch src/models/sentence_ranker/trainer.py
touch src/models/sentence_ranker/inference.py

touch src/models/ner/__init__.py
touch src/models/ner/bert_ner.py
touch src/models/ner/entity_extractor.py
touch src/models/ner/trainer.py
touch src/models/ner/inference.py

touch src/models/generation/__init__.py
touch src/models/generation/llm_generator.py
touch src/models/generation/template_engine.py
touch src/models/generation/prompt_builder.py
touch src/models/generation/trainer.py
touch src/models/generation/inference.py

# Data
mkdir -p src/data/dictionary
mkdir -p src/data/templates

touch src/data/__init__.py
touch src/data/dataset.py
touch src/data/dataloader.py
touch src/data/collator.py
touch src/data/weak_supervision_dataset.py

touch src/data/dictionary/__init__.py
touch src/data/dictionary/loader.py
touch src/data/dictionary/builder.py
touch src/data/dictionary/enricher.py
touch src/data/dictionary/validator.py

touch src/data/templates/__init__.py
touch src/data/templates/loader.py
touch src/data/templates/builder.py
touch src/data/templates/validator.py

# Pipeline
mkdir -p src/pipeline

touch src/pipeline/__init__.py
touch src/pipeline/base.py
touch src/pipeline/weak_supervision.py
touch src/pipeline/production.py
touch src/pipeline/multimodal.py
touch src/pipeline/orchestrator.py
touch src/pipeline/streaming.py

# Quality
mkdir -p src/quality/validators

touch src/quality/__init__.py
touch src/quality/validators/__init__.py
touch src/quality/validators/completeness.py
touch src/quality/validators/consistency.py
touch src/quality/validators/medical_logic.py
touch src/quality/validators/noise_detection.py
touch src/quality/scoring.py
touch src/quality/reviewer.py

# Postprocessing
mkdir -p src/postprocessing

touch src/postprocessing/__init__.py
touch src/postprocessing/spellcheck.py
touch src/postprocessing/grammar.py
touch src/postprocessing/unit_normalizer.py
touch src/postprocessing/number_formatter.py
touch src/postprocessing/abbreviation_expander.py

# Structures
mkdir -p src/structures

touch src/structures/__init__.py
touch src/structures/schemas.py
touch src/structures/entities.py
touch src/structures/reports.py
touch src/structures/builders.py

# Export
mkdir -p src/export

touch src/export/__init__.py
touch src/export/base.py
touch src/export/json_exporter.py
touch src/export/pdf_generator.py
touch src/export/word_exporter.py
touch src/export/hl7_formatter.py
touch src/export/dicom_sr.py

# Learning
mkdir -p src/learning

touch src/learning/__init__.py
touch src/learning/uncertainty.py
touch src/learning/feedback_collector.py
touch src/learning/correction_store.py
touch src/learning/retrainer.py

# Utils
mkdir -p src/utils

touch src/utils/__init__.py
touch src/utils/helpers.py
touch src/utils/metrics.py
touch src/utils/validators.py
touch src/utils/device.py

# ============================================
# services (microservices)
# ============================================
echo "Creating services structure..."

mkdir -p services

touch services/__init__.py

# Controller (existing)
mkdir -p services/controller/routes
mkdir -p services/controller/middleware
mkdir -p services/controller/schemas

touch services/controller/__init__.py
touch services/controller/main.py
touch services/controller/config.py
touch services/controller/routes/__init__.py
touch services/controller/routes/health.py
touch services/controller/routes/transcription.py
touch services/controller/routes/websocket.py
touch services/controller/routes/admin.py
touch services/controller/middleware/__init__.py
touch services/controller/middleware/auth.py
touch services/controller/middleware/cors.py
touch services/controller/middleware/rate_limit.py
touch services/controller/schemas/__init__.py
touch services/controller/schemas/request.py
touch services/controller/schemas/response.py
touch services/controller/dependencies.py
touch services/controller/requirements.txt
touch services/controller/README.md

# STT (existing)
mkdir -p services/stt/app

touch services/stt/__init__.py
touch services/stt/app/__init__.py
touch services/stt/app/main.py
touch services/stt/app/config.py
touch services/stt/requirements.txt
touch services/stt/README.md

# Core LLM (existing)
mkdir -p services/core_llm

touch services/core_llm/__init__.py
touch services/core_llm/main.py
touch services/core_llm/model.py
touch services/core_llm/config.py
touch services/core_llm/requirements.txt
touch services/core_llm/README.md

# Evaluation (existing)
mkdir -p services/evaluation/tests

touch services/evaluation/__init__.py
touch services/evaluation/main.py
touch services/evaluation/metrics.py
touch services/evaluation/config.py
touch services/evaluation/requirements.txt
touch services/evaluation/README.md

# Content Filter Service (NEW)
mkdir -p services/content_filter_service

touch services/content_filter_service/__init__.py
touch services/content_filter_service/main.py
touch services/content_filter_service/filter.py
touch services/content_filter_service/config.py
touch services/content_filter_service/requirements.txt
touch services/content_filter_service/README.md

# NER Service (NEW)
mkdir -p services/ner_service

touch services/ner_service/__init__.py
touch services/ner_service/main.py
touch services/ner_service/extractor.py
touch services/ner_service/config.py
touch services/ner_service/requirements.txt
touch services/ner_service/README.md

# Dictionary Service (NEW)
mkdir -p services/dictionary_service

touch services/dictionary_service/__init__.py
touch services/dictionary_service/main.py
touch services/dictionary_service/enricher.py
touch services/dictionary_service/config.py
touch services/dictionary_service/requirements.txt
touch services/dictionary_service/README.md

# QA Service (NEW)
mkdir -p services/qa_service

touch services/qa_service/__init__.py
touch services/qa_service/main.py
touch services/qa_service/validator.py
touch services/qa_service/config.py
touch services/qa_service/requirements.txt
touch services/qa_service/README.md

# ============================================
# training
# ============================================
echo "Creating training structure..."

mkdir -p training/weak_supervision

touch training/__init__.py

# Weak supervision (NEW)
touch training/weak_supervision/__init__.py
touch training/weak_supervision/step1_create_transcripts.py
touch training/weak_supervision/step2_align_to_reports.py
touch training/weak_supervision/step3_create_labels.py
touch training/weak_supervision/step4_train_content_filter.py
touch training/weak_supervision/step5_train_sentence_ranker.py
touch training/weak_supervision/evaluate_alignment.py

# Other training scripts
touch training/train_asr.py
touch training/train_content_filter.py
touch training/train_sentence_ranker.py
touch training/train_ner.py
touch training/train_llm.py
touch training/data_preparation.py
touch training/augmentation.py
touch training/callbacks.py

# ============================================
# evaluation
# ============================================
echo "Creating evaluation structure..."

mkdir -p evaluation

touch evaluation/__init__.py
touch evaluation/evaluate_asr.py
touch evaluation/evaluate_content_filter.py
touch evaluation/evaluate_sentence_ranker.py
touch evaluation/evaluate_ner.py
touch evaluation/evaluate_generation.py
touch evaluation/evaluate_end2end.py
touch evaluation/noise_analysis.py
touch evaluation/alignment_quality.py
touch evaluation/clinical_validation.py

# ============================================
# benchmark (existing structure)
# ============================================
echo "Creating benchmark structure..."

mkdir -p benchmark

touch benchmark/__init__.py
touch benchmark/runner.py
touch benchmark/plan.py
touch benchmark/tiers.py
touch benchmark/scoring.py
touch benchmark/notebook.ipynb
touch benchmark/README.md

# ============================================
# scripts
# ============================================
echo "Creating scripts structure..."

mkdir -p scripts

touch scripts/setup_environment.sh
touch scripts/download_models.py
touch scripts/build_dictionaries.py
touch scripts/prepare_weak_supervision.sh
touch scripts/analyze_noise_patterns.py
touch scripts/create_noise_dictionary.py
touch scripts/validate_data.py
touch scripts/train_all.sh
touch scripts/deploy.sh

chmod +x scripts/*.sh

# ============================================
# monitoring
# ============================================
echo "Creating monitoring structure..."

mkdir -p monitoring/dashboards
mkdir -p monitoring/prometheus

touch monitoring/__init__.py
touch monitoring/metrics_collector.py
touch monitoring/alerting.py
touch monitoring/profiling.py
touch monitoring/dashboards/inference.json
touch monitoring/dashboards/filtering_performance.json
touch monitoring/dashboards/training.json
touch monitoring/prometheus/prometheus.yml

# ============================================
# tests
# ============================================
echo "Creating tests structure..."

mkdir -p tests/unit
mkdir -p tests/integration
mkdir -p tests/performance
mkdir -p tests/fixtures

touch tests/__init__.py
touch tests/conftest.py

# Unit tests
touch tests/unit/test_preprocessing.py
touch tests/unit/test_alignment.py
touch tests/unit/test_content_filter.py
touch tests/unit/test_noise_detection.py
touch tests/unit/test_sentence_ranker.py
touch tests/unit/test_ner.py
touch tests/unit/test_dictionary.py
touch tests/unit/test_templates.py
touch tests/unit/test_quality.py
touch tests/unit/test_utils.py

# Integration tests
touch tests/integration/test_weak_supervision.py
touch tests/integration/test_production_pipeline.py
touch tests/integration/test_services.py
touch tests/integration/test_api.py
touch tests/integration/test_end2end.py

# Performance tests
touch tests/performance/test_latency.py
touch tests/performance/test_throughput.py
touch tests/performance/test_memory.py

# Fixtures
cat > tests/fixtures/.gitkeep << EOF
# Test fixtures directory
# Place sample audio, transcripts, and reports here
EOF

# ============================================
# notebooks
# ============================================
echo "Creating notebooks structure..."

mkdir -p notebooks

touch notebooks/01_noise_analysis.ipynb
touch notebooks/02_weak_supervision_demo.ipynb
touch notebooks/03_alignment_visualization.ipynb
touch notebooks/04_error_analysis.ipynb
touch notebooks/05_model_comparison.ipynb

# ============================================
# docker
# ============================================
echo "Creating docker structure..."

mkdir -p docker/nginx/ssl

touch docker/Dockerfile
touch docker/Dockerfile.gpu
touch docker/Dockerfile.cpu
touch docker/docker-compose.yml
touch docker/docker-compose.dev.yml
touch docker/docker-compose.prod.yml
touch docker/.dockerignore
touch docker/nginx/nginx.conf

cat > docker/nginx/ssl/.gitkeep << EOF
# SSL certificates directory
EOF

# ============================================
# deployment
# ============================================
echo "Creating deployment structure..."

mkdir -p deployment/kubernetes
mkdir -p deployment/terraform/modules
mkdir -p deployment/ansible/roles

touch deployment/kubernetes/namespace.yaml
touch deployment/kubernetes/deployment.yaml
touch deployment/kubernetes/service.yaml
touch deployment/kubernetes/ingress.yaml
touch deployment/kubernetes/configmap.yaml
touch deployment/kubernetes/secrets.yaml
touch deployment/kubernetes/hpa.yaml

touch deployment/terraform/main.tf
touch deployment/terraform/variables.tf
touch deployment/terraform/outputs.tf

touch deployment/ansible/playbook.yml
touch deployment/ansible/inventory.ini

# ============================================
# Root files
# ============================================
echo "Creating root configuration files..."

touch .env.example
touch .gitignore
touch .pre-commit-config.yaml
touch requirements.txt
touch requirements-dev.txt
touch setup.py
touch pyproject.toml
touch LICENSE
touch README.md
touch CITATION.cff

# ============================================
# .gitignore content
# ============================================
cat > .gitignore << 'EOF'
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Jupyter
.ipynb_checkpoints/
*.ipynb_checkpoints

# Data (large files)
data/raw/audio/
data/raw/reports/
data/processed/
*.wav
*.mp3
*.mp4

# Models (large files)
models/
*.bin
*.safetensors
*.pt
*.pth
*.onnx

# Logs
logs/
*.log

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db

# Temporary
tmp/
temp/
*.tmp

# Coverage
.coverage
htmlcov/

# MyPy
.mypy_cache/

# Pytest
.pytest_cache/

# Docker
*.dockerfile.swp
EOF

# ============================================
# .env.example content
# ============================================
cat > .env.example << 'EOF'
# Project Configuration
PROJECT_NAME=BuAli
ENVIRONMENT=development

# API
API_HOST=0.0.0.0
API_PORT=9002
API_WORKERS=4
INTERNAL_API_TOKEN=your-secret-token-here

# GPU
CUDA_VISIBLE_DEVICES=0
TORCH_HOME=./models

# Services
STT_SERVICE_URL=http://localhost:8000
LLM_SERVICE_URL=http://localhost:8001
EVAL_SERVICE_URL=http://localhost:8002
CONTENT_FILTER_SERVICE_URL=http://localhost:8003
NER_SERVICE_URL=http://localhost:8004
DICT_SERVICE_URL=http://localhost:8005
QA_SERVICE_URL=http://localhost:8006

# Model Paths
ASR_MODEL_PATH=./models/asr/whisper-large-v3-medical
CONTENT_FILTER_MODEL_PATH=./models/content_filter/bert-fa-content-filter
SENTENCE_RANKER_MODEL_PATH=./models/sentence_ranker/ranker-v1
NER_MODEL_PATH=./models/ner/bert-fa-medical-ner
LLM_MODEL_PATH=./models/llm/mixtral-medical-lora

# Database (optional)
DATABASE_URL=postgresql://user:password@localhost:5432/ultrasound_db
REDIS_URL=redis://localhost:6379/0

# Storage
UPLOAD_DIR=./data/uploads
OUTPUT_DIR=./data/outputs
MAX_UPLOAD_SIZE=104857600

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Monitoring
PROMETHEUS_ENABLED=true
PROMETHEUS_PORT=9090
GRAFANA_PORT=3000

# Hugging Face
HF_TOKEN=your-huggingface-token-here
EOF

# ============================================
# requirements.txt (basic dependencies)
# ============================================
cat > requirements.txt << 'EOF'
# Core
torch>=2.1.0
transformers>=4.36.0
torchaudio>=2.1.0
accelerate>=0.25.0
bitsandbytes>=0.41.3
sentencepiece>=0.1.99

# NLP
hazm>=0.7.0
parsivar>=0.2.3
spacy>=3.7.0

# Audio
librosa>=0.10.1
soundfile>=0.12.1
pydub>=0.25.1

# API
fastapi>=0.104.1
uvicorn[standard]>=0.24.0
pydantic>=2.5.0
python-multipart>=0.0.6

# Data
pandas>=2.1.0
numpy>=1.24.0
scikit-learn>=1.3.0

# Utils
pyyaml>=6.0
python-dotenv>=1.0.0
tqdm>=4.66.0

# Monitoring
prometheus-client>=0.19.0

# Export
reportlab>=4.0.0
python-docx>=1.1.0
EOF

# ============================================
# requirements-dev.txt
# ============================================
cat > requirements-dev.txt << 'EOF'
-r requirements.txt

# Testing
pytest>=7.4.0
pytest-cov>=4.1.0
pytest-asyncio>=0.21.0
pytest-mock>=3.12.0

# Code quality
black>=23.0.0
isort>=5.12.0
flake8>=6.1.0
mypy>=1.7.0
pylint>=3.0.0

# Pre-commit
pre-commit>=3.5.0

# Jupyter
jupyter>=1.0.0
ipykernel>=6.26.0
matplotlib>=3.8.0
seaborn>=0.13.0

# Documentation
mkdocs>=1.5.0
mkdocs-material>=9.4.0
EOF

## ============================================
## Basic README.md
## ============================================
#cat > README.md << 'EOF'
## Medical Ultrasound Reporting Assistant
#
#AI-powered system for generating structured radiology reports from noisy medical dictations.
#
### Features
#
#- **Intelligent Noise Filtering**: Handles "نه برگرد عقب" and other filler words
#- **Weak Supervision**: Learns from (Audio, Final Report) pairs
#- **Content Classification**: Separates relevant content from noise
#- **Entity Extraction**: Medical NER from filtered text
#- **Template-based Reports**: Structured, consistent outputs
#
### Quick Start
#
#```bash
## Clone
#git clone https://github.com/nezamtrm/BuAli
#cd medical-ultrasound-assistant
#
## Setup
#bash scripts/setup_environment.sh
#
## Install
#pip install -r requirements.txt
#
## Prepare data
## Place your audio and reports in data/raw/
## Then run:
#bash scripts/prepare_weak_supervision.sh
#
## Train models
#python training/weak_supervision/step1_create_transcripts.py
#python training/weak_supervision/step2_align_to_reports.py
#python training/weak_supervision/step3_create_labels.py
#python training/weak_supervision/step4_train_content_filter.py
#
## Run inference
#python -m src.pipeline.production --audio exam.wav --output report.json